version: 2
jobs:
 build:
   working_directory: ~/adder
   docker:
     - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

   steps:
     - checkout

     # try to restore from cache
     - run: sudo chown -R circleci:circleci /usr/local/bin
     - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
     - restore_cache:
        key: ci-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

     - run:
        command: |
            sudo pip install pipenv
            pipenv install

     # save cache
     - save_cache:
         key: ci-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
         paths:
           - ".venv"
           - "/usr/local/bin"
           - "/usr/local/lib/python3.7/site-packages"

     - run:
        command: |
          pipenv run python -m unittest discover ./tests
